services:
  app: # docker compose up --build で起動
    build: .
    # ports:
    #  - "5001:5000"
    environment:
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY?`RAILS_MASTER_KEY`をセットしてください}"
    # volumes:
      # - .:/rails
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # profiles:
    #   - production # docker compose up --build --profile production で起動
  # mac-build: # WIP
  #   image: registry.docker.com/library/ruby:3.3.4-slim
  #   volumes:
  #     - .:/rails
  #   working_dir: /rails
  #   command: apt update && apt install build-essential clang && export CC=/usr/bin/clang && export CXX=/usr/bin/clang++ && bundle update && bundle install # 適当
  haproxy:
    image: haproxy:2.4
    ports:
      - "80:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - app
      - maintenance
  maintenance:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./public/_maintenance:/usr/local/apache2/htdocs/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: circlehub
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD?`POSTGRES_PASSWORD`をセットしてください}"
      POSTGRES_DB: circlehub_production
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - .db/postgres/init:/docker-entrypoint-initdb.d

volumes:
  db-data:
