version: "3"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/rails
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: circlehub
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD?`POSTGRES_PASSWORD`をセットしてください}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - .db/postgres/init:/docker-entrypoint-initdb.d