default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode # 追加

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: circlehub_development
  username: username
  password: password

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: circlehub_test
  username: username
  password: password

production:
  <<: *default
  # database: db/production.sqlite3 変更
  # host: host.docker.internal
  host: db
  port: 5432
  database: circlehub_production
  username: <%= Rails.application.credentials.postgres&.dig(:username) %>
  password: <%= Rails.application.credentials.postgres&.dig(:password) %>
  # username: <%= ENV['PG_DATABASE_USERNAME'] %>
  # password: <%= ENV['PG_DATABASE_PASSWORD'] %>

# 参考
# create USER username with password 'password';
# create DATABASE CircleHub_development;
# create DATABASE CircleHub_test;
# grant ALL PRIVILEGES ON DATABASE CircleHub_development TO username;
# grant ALL PRIVILEGES ON DATABASE CircleHub_test TO username;
# alter DATABASE CircleHub_development OWNER TO username; 
# alter DATABASE CircleHub_test OWNER TO username; 